# Generated by Django 2.2.7 on 2020-05-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_approved_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_reply',
        ),
    ]
